package com.omkashyap.com.backend.type;

public enum EmailTypeEnum {

  SELLER_OTP,
  WALLET_OTP,
  ORDER_CONFIRMATION,
  ORDER_CANCELLATION,
  ORDER_EXCHANGE,
  ORDER_RETURN,
  PAYMENT_SUCCESS,
  PAYMENT_FAILED,
  USER_WELCOME,
  SELLER_WELCOME,
  AFFILIATE_WELCOME,
  WALLET_WELCOME

}
