spring:
  security.oauth2.client:
    registration:
      google:
        client-id: 853872538696-dk1dfes9t86cko1o4rn7hppmf66n70jb.apps.googleusercontent.com
        client-secret: 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
  mail:
    host: smtp.gmail.com
    port: 587
    username: om.kashyap2902@gmail.com
    password: luaenmpubsataptp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
